#MS Energy Usage Config. This config is synced from server to client.
[storage]
	#Energy per operation in Joules of: Osmium Compressor
	# Default: 100
	# Range: 0 ~ 9223372036854775807
	airCompressor = 100
	#Energy per operation in Joules of: Osmium Compressor
	# Default: 1000
	# Range: 0 ~ 9223372036854775807
	radiationIrradiator = 1000
	#Energy per operation in Joules of: Osmium Compressor
	# Default: 500
	# Range: 0 ~ 9223372036854775807
	adsorptionTypeSeawaterMetalExtractor = 500
	#Energy per operation in Joules of: Osmium Compressor
	# Default: 100
	# Range: 0 ~ 9223372036854775807
	organicLiquidExtractor = 100
	#Energy per operation in Joules of: Osmium Compressor
	# Default: 100
	# Range: 0 ~ 9223372036854775807
	seawaterPump = 100
