#Science Energy Storage Config. This config is synced from server to client.
[storage]
	#Base energy storage in Joules of: Combiner
	# Default: 40000
	# Range: 1 ~ 9223372036854775807
	airCompressor = 40000
	#Base energy storage in Joules of: Combiner
	# Default: 40000
	# Range: 1 ~ 9223372036854775807
	radiation_irradiator = 40000
	#Base energy storage in Joules of: Combiner
	# Default: 40000
	# Range: 1 ~ 9223372036854775807
	adsorption = 40000
	#Base energy storage in Joules of: Combiner
	# Default: 40000
	# Range: 1 ~ 9223372036854775807
	seawaterPump = 40000
